swagger: '2.0'
info:
  description: ''
  version: 1.0.0
  title: RDMO JSON API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8000'
basePath: /api/v1
schemes:
  - http
paths:
  /accounts/users/:
    get:
      tags:
        - accounts
      summary: List users
      parameters:
        - name: username
          in: query
          description: Filter by username.
          required: false
          type: string
        - name: email
          in: query
          description: Filter by email.
          required: false
          type: string
        - name: project
          in: query
          description: Filter by project ID.
          required: false
          type: integer
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/user'
        '403':
          description: Forbidden
  '/accounts/users/{id}':
    get:
      tags:
        - accounts
      summary: Retrieve user
      parameters:
        - name: id
          in: path
          description: The ID of the user.
          required: true
          type: integer
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/user'
        '403':
          description: Forbidden
        '404':
          description: Not found
  /conditions/conditions/:
    get:
      tags:
        - conditions
      summary: List conditions
      parameters:
        - name: uri
          in: query
          description: Filter by URI.
          required: false
          type: string
        - name: key
          in: query
          description: Filter by key.
          required: false
          type: string
        - name: source
          in: query
          description: Filter by source attribute ID.
          required: false
          type: integer
        - name: relation
          in: query
          description: Filter by relation.
          required: false
          type: integer
        - name: target_text
          in: query
          description: Filter by target text.
          required: false
          type: string
        - name: target_option
          in: query
          description: Filter by target option ID.
          required: false
          type: integer
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/condition'
        '403':
          description: Forbidden
  '/conditions/conditions/{id}':
    get:
      tags:
        - conditions
      summary: Retrieve conditions
      parameters:
        - name: id
          in: path
          description: The ID of the condition.
          required: true
          type: integer
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/condition'
        '403':
          description: Forbidden
        '404':
          description: Not found
  /domain/entities/:
    get:
      tags:
        - domain
      summary: List entities
      parameters:
        - name: uri
          in: query
          description: Filter by URI.
          required: false
          type: string
        - name: path
          in: query
          description: Filter by path.
          required: false
          type: string
        - name: key
          in: query
          description: Filter by key.
          required: false
          type: string
        - name: parent
          in: query
          description: Filter by parent entity ID.
          required: false
          type: integer
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/entity'
        '403':
          description: Forbidden
  '/domain/entities/{id}':
    get:
      tags:
        - domain
      summary: Retrieve entity
      parameters:
        - name: id
          in: path
          description: The ID of the entity
          required: true
          type: integer
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/entity'
        '403':
          description: Forbidden
        '404':
          description: Not found
  /domain/attributes/:
    get:
      tags:
        - domain
      summary: List attributes
      parameters:
        - name: uri
          in: query
          description: Filter by URI.
          required: false
          type: string
        - name: path
          in: query
          description: Filter by path.
          required: false
          type: string
        - name: key
          in: query
          description: Filter by key.
          required: false
          type: string
        - name: parent
          in: query
          description: Filter by parent entity ID.
          required: false
          type: integer
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/attribute'
        '403':
          description: Forbidden
  '/domain/attribute/{id}':
    get:
      tags:
        - domain
      summary: Retrieve attribute
      parameters:
        - name: id
          in: path
          description: The ID of the attribute
          required: true
          type: integer
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/attribute'
        '403':
          description: Forbidden
        '404':
          description: Not found
  /options/optionset/:
    get:
      tags:
        - options
      summary: List option sets
      parameters:
        - name: uri
          in: query
          description: Filter by URI.
          required: false
          type: string
        - name: key
          in: query
          description: Filter by key.
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/optionset'
        '403':
          description: Forbidden
  '/options/optionset/{id}':
    get:
      tags:
        - options
      summary: Retrieve option set
      parameters:
        - name: id
          in: path
          description: The ID of the option set
          required: true
          type: integer
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/optionset'
        '403':
          description: Forbidden
        '404':
          description: Not found
  /options/options/:
    get:
      tags:
        - options
      summary: List options
      parameters:
        - name: uri
          in: query
          description: Filter by URI.
          required: false
          type: string
        - name: path
          in: query
          description: Filter by path.
          required: false
          type: string
        - name: key
          in: query
          description: Filter by key.
          required: false
          type: string
        - name: optionset
          in: query
          description: Filter by parent optionset ID.
          required: false
          type: integer
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/option'
        '403':
          description: Forbidden
  '/options/options/{id}':
    get:
      tags:
        - options
      summary: Retrieve option
      parameters:
        - name: id
          in: path
          description: The ID of the options
          required: true
          type: integer
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/option'
        '403':
          description: Forbidden
        '404':
          description: Not found
definitions:
  user:
    type: object
    properties:
      id:
        description: The ID of the user.
        type: integer
      username:
        description: The username of the user.
        type: string
      first_name:
        description: The first name of the user.
        type: string
      last_name:
        description: The last name of the user.
        type: string
      email:
        description: The email of the user.
        type: string
  condition:
    type: object
    properties:
      id:
        description: The ID of this condition.
        type: integer
      uri:
        description: The Uniform Resource Identifier of this condition.
        type: string
        format: uri
      uri_prefix:
        description: The prefix for the URI of this condition.
        type: string
      key:
        description: The internal identifier of this condition.
        type: string
      comment:
        description: Additional internal information about this condition.
        type: string
      source:
        description: The Attribute this condition is evaluating.
        type: string
        format: url
      relation:
        description: The Relation this condition is using.
        type: string
      target_text:
        description: >-
          If using a regular attibute, the text value this condition is checking
          against.
        type: string
      target_option:
        description: >-
          If using an options attribute, the option this condition is checking
          against.
        type: string
        format: url
  entity:
    type: object
    properties:
      id:
        description: The ID of this entity.
        type: integer
      uri:
        description: The Uniform Resource Identifier of this entity.
        type: string
        format: uri
      uri_prefix:
        description: The prefix for the URI of this entity.
        type: string
      path:
        description: The path part of the URI of this entity.
        type: string
      key:
        description: The internal identifier of this entity.
        type: string
      comment:
        description: Additional internal information about this entity.
        type: string
      is_collection:
        description: Designates whether this entity is a collection.
        type: boolean
      conditions:
        description: List of conditions evaluated for this entity.
        type: array
        items:
          type: string
          format: url
      parent:
        description: Parent entity in the domain model.
        type: string
        format: url
      children:
        description: List of child entities/attributes in the domain model.
        type: array
        items:
          type: string
          format: url
  attribute:
    type: object
    properties:
      id:
        description: The ID of this attribute.
        type: integer
      uri:
        description: The Uniform Resource Identifier of this attribute.
        type: string
        format: uri
      uri_prefix:
        description: The prefix for the URI of this attribute.
        type: string
      path:
        description: The path part of the URI of this attribute.
        type: string
      key:
        description: The internal identifier of this attribute.
        type: string
      comment:
        description: Additional internal information about this attribute.
        type: string
      value_type:
        description: Type of value for this attribute.
        type: string
      unit:
        description: Unit for this attribute.
        type: string
      is_collection:
        description: Designates whether this attribute is a collection.
        type: boolean
      range:
        $ref: '#/definitions/range'
      optionsets:
        description: List of optionsets used for this attribute.
        type: array
        items:
          type: string
          format: url
      conditions:
        description: List of conditions evaluated for this attribute.
        type: array
        items:
          type: string
          format: url
      parent:
        description: Parent entity in the domain model.
        type: string
        format: url
  range:
    type: object
    properties:
      id:
        description: The ID of this attribute.
        type: integer
      minimum:
        description: Minimal value for this attribute.
        type: number
        format: float
      maximum:
        description: Maximum value for this attribute.
        type: number
        format: float
      step:
        description: Step in which this attribute can be incremented/decremented.
        type: number
        format: float
  optionset:
    type: object
    properties:
      id:
        description: The ID ot this option set.
        type: integer
      uri:
        description: The Uniform Resource Identifier of this option set.
        type: string
        format: uri
      uri_prefix:
        description: The prefix for the URI of this option set.
        type: string
      key:
        description: The internal identifier of this option set.
        type: string
      comment:
        description: Additional internal information about this option set.
        type: string
      order:
        description: The position of this option set in lists.
        type: integer
      conditions:
        type: array
        description: List of conditions evaluated for this option set.
        items:
          type: string
          format: url
      options:
        type: array
        description: List of options in this optionset.
        items:
          type: string
          format: url
  option:
    type: object
    properties:
      id:
        description: The ID ot this option.
        type: integer
      uri:
        description: The Uniform Resource Identifier of this option.
        type: string
        format: uri
      uri_prefix:
        description: The prefix for the URI of this option.
        type: string
      key:
        description: The internal identifier of this option.
        type: string
      comment:
        description: Additional internal information about this option.
        type: string
      order:
        description: The position of this option in lists.
        type: integer
      text_en:
        description: The English text displayed for this option.
        type: string
      text_de:
        description: The German text displayed for this option.
        type: string
      additional_input:
        description: Designates whether an additional input is possible for this option.
        type: boolean
      optionset:
        description: The option set this option belongs to.
        type: string
        format: url
